AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopic:
    Description: What is the SNS topic ARN that you would like to associate with this
      lambda function.
    Type: String
Resources:
  SetPolicyStatements:
    Properties:
      CodeUri: s3://363723026716-us-east-1-code/4f5b7aaabfcbd8cf34ea705dbf88b3f3
      Events:
        MyTopic:
          Properties:
            Topic:
              Ref: SNSTopic
          Type: SNS
      FunctionName: set_policy_statements
      Handler: set_policy_statements.lambda_handler
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - kms:Create*
          - kms:Describe*
          - kms:Enable*
          - kms:List*
          - kms:Put*
          - kms:Update*
          - kms:Revoke*
          - kms:Disable*
          - kms:Get*
          - kms:Delete*
          - kms:TagResource
          - kms:UntagResource
          - kms:ScheduleKeyDeletion
          - kms:CancelKeyDeletio
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      - Statement:
        - Action:
          - secretsmanager:PutResourcePolicy
          - secretsmanager:PutSecretValue
          - secretsmanager:RotateSecret
          - secretsmanager:UpdateSecret
          - secretsmanager:DescribeSecret
          Effect: Allow
          Resource: arn:aws:secretsmanager:*:*:secret:*
        Version: '2012-10-17'
      - Statement:
        - Action:
          - s3:PutBucketPublicAccessBlock
          - s3:PutBucketAcl
          - s3:PutBucketPolicy
          - s3:DeleteBucketPolicy
          Effect: Allow
          Resource: arn:aws:s3:::*
        Version: '2012-10-17'
      - Statement:
        - Action:
          - s3:ObjectOwnerOverrideToBucketOwner
          - s3:PutObjectVersionAcl
          - s3:PutObjectAcl
          Effect: Allow
          Resource: arn:aws:s3:::*/*
        Version: '2012-10-17'
      - Statement:
        - Action:
          - iam:GenerateCredentialReport
          - iam:GenerateServiceLastAccessedDetails
          - iam:Get*
          - iam:List*
          - iam:SimulateCustomPolicy
          - iam:SimulatePrincipalPolicy
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      Runtime: python3.7
      Timeout: 360
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
