AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  SNSTopic:
    Type: String
    Description: What is the SNS topic ARN that you would like to associate with this lambda function.

Resources:
  SetPolicyStatements:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: set_policy_statements.lambda_handler
      FunctionName: set_policy_statements
      Runtime: python3.7
      Timeout: 360
      CodeUri:
         Bucket: !Sub '${AWS::AccountId}-${AWS::Region}-code'
         Key: 'set-policy-statement.zip'
      Events:
        MyTopic:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                 - kms:Create*
                 - kms:Describe*
                 - kms:Enable*
                 - kms:List*
                 - kms:Put*
                 - kms:Update*
                 - kms:Revoke*
                 - kms:Disable*
                 - kms:Get*
                 - kms:Delete*
                 - kms:TagResource
                 - kms:UntagResource
                 - kms:ScheduleKeyDeletion
                 - kms:CancelKeyDeletio
              Resource: '*'
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:PutResourcePolicy
                - secretsmanager:PutSecretValue
                - secretsmanager:RotateSecret
                - secretsmanager:UpdateSecret
                - secretsmanager:DescribeSecret
              Resource: 'arn:aws:secretsmanager:*:*:secret:*'
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:PutBucketPublicAccessBlock
                - s3:PutBucketAcl
                - s3:PutBucketPolicy
                - s3:DeleteBucketPolicy
              Resource: 'arn:aws:s3:::*'
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:ObjectOwnerOverrideToBucketOwner
                - s3:PutObjectVersionAcl
                - s3:PutObjectAcl
              Resource: 'arn:aws:s3:::*/*'
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - iam:GenerateCredentialReport
                - iam:GenerateServiceLastAccessedDetails
                - iam:Get*
                - iam:List*
                - iam:SimulateCustomPolicy
                - iam:SimulatePrincipalPolicy
              Resource: '*'
